flywheel:
  streams:
    - name: main-line
      branches:
        - name: e2e-develop
          prerelease: dev
          auto_merge: [fix, fix!, chore, style, test, docs]
        - name: e2e-staging
          prerelease: rc
          auto_merge: [fix, chore]
        - name: e2e-main
          auto_merge: []

    - name: customer-acme
      branches:
        - name: e2e-customer-acme
          prerelease: acme
          auto_merge: [fix, fix!, chore]

    - name: integration
      branches:
        - name: integration-test-base
          prerelease: int
          auto_merge: [fix, chore, perf, style, test]

  merge_strategy: squash
  initial_version: 0.1.0
